### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by Xf0ur** [ardi69/softwarePIP#1]
Can you upload the Makefile in order to compile it?
Thx.

**Comment by ardi69** [comment]
I'm sorry
I made this Plugin for Enigma2 long time ago with the ([oe-alliance](https://github.com/oe-alliance))-build-enviroment.
I only published the code because I was asked for it.
I think a Makefile is not needed ... wait ... 
see my last commit 7a5b4378876fbadefbb63d21f229a17a1dad6ccf. I have added a bb-file
the bb-file must be edited. currently links to my home svn-server yoda
build with:
```
cd ~/oealliance/build-enviroment/builds/openatv/release/inihde2/
source env.source
bitbake enigma2-plugin-systemplugins-softwarepip || exit 1
cp ~/oealliance/build-enviroment/builds/openatv/release/inihde2/tmp/deploy/ipk/mips32el/enigma2-plugin-systemplugins-softwarepip_*mips32el.ipk ~
```
or
```
cd ~/oealliance/build-enviroment/builds/openatv/release/vuuno4k/
source env.source
bitbake enigma2-plugin-systemplugins-softwarepip || exit 1
cp ~/oealliance/build-enviroment/builds/openatv/release/vuuno4k/tmp/deploy/ipk/cortexa15hf-neon-vfpv4/enigma2-plugin-systemplugins-softwarepip_*.ipk ~
```

**Comment by Xf0ur** [comment]
Thank you.
One last question, i don't use openatv so dunno what is the following url used for?
http://openatv:8001/1:0:19:283D:3FB:1:C00000:0:0:0

**Comment by ardi69** [comment]
Hello,
http://openatv:8001/1:0:19:283D:3FB:1:C00000:0:0:0
this is a stream. 1:0:19:283D:3FB:1:C00000:0:0:0 is the coded tv channel
you can see tv e.g with VideoLAN

**Comment by Xf0ur** [comment]
Hi, 
Yes i know that you can download a whole bouquet playlist off OpenWebif and watch it in VLC.
I was confused what does that specific url do specially it should use the receiver ip address same as in plugin.py 
http://127.0.0.1:8001
Instead of
http://openatv:8001
Anyway, after i googled it, i found out that 1:0:19:283D:3FB:1:C00000:0:0:0: is  Das Erste HD channel.

**Comment by ardi69** [comment]
I don't understand. Where is this link from?

**Comment by Xf0ur** [comment]
It's in main.cpp.

**Comment by ardi69** [comment]
Ohhh. Ahhh. ☝😀 ...
... i remember.
I programmed and tested SoftwarePIP on my PC. If SoftwarePIP was started without arguments, then it took the stream from my OpenATV box (network name: "openatv").
“Das Erste HD” is an HD channel. This is for testing purposes only.
The plugin always opens softwarePIP with arguments.
`softwarepip -i streamuri
`

**Comment by Xf0ur** [comment]
Alright,
That solved the mystery 😀
